### ISSUE TITLE
Translate README to Arabic - ترجمة ال README للعربية

### ISSUE THREAD

**Issue by amrrbakry** [fawry-api/fawry#7]

**Comment by aburay** [comment]
>

**Comment by fabiosoaresv** [comment]
@AmrAdelKhalil Can you check my PR please? https://github.com/fawry-api/fawry/pull/10

**Comment by fabiosoaresv** [comment]
Can you check the label please? Because I received this message from site Hacktoberfest:
![image](https://user-images.githubusercontent.com/31450742/96177408-3a758c00-0f04-11eb-80d1-473886884081.png)

Follow the legend about this:
![image](https://user-images.githubusercontent.com/31450742/96177465-4f521f80-0f04-11eb-8288-9633e707e35b.png)

**Comment by amrrbakry** [comment]
add the topic to the repo 👍
